### ISSUE TITLE
Mapping issue when using relations in domain entities

### ISSUE THREAD

**Issue by aurelmegn** [Nikoms/clean-architecture-example#4]
Hello, 
I would like to thank you first for the proposed architecture.
I decided to use it for a class project and I noticed that when I start using relationship between doctrine entities and I want to have the relation into my domaine entities, they is a problem.

For instance, when I have as Entity of Doctrine:
```php
/**
 * @ORM\Entity(repositoryClass="App\Infrastructure\Repository\OrderRepository")
 * @ORM\Table(name="orders")
 */
class OrderEntity
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\ManyToOne(targetEntity="App\Infrastructure\Entity\ProductEntity")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    /**
     * @ORM\ManyToOne(targetEntity="App\Infrastructure\Entity\BasketEntity", inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $basket;

}
```
```php
And as Entity of my domain:

class Order
{
    public $id;

    public $createdAt;

    public $quantity;

    public $product_id;

    public $basket_id;
    
    public function __construct(IOrderRepository $orderRepository)
    {
        $this->createdAt = Utils::createDateTime();
        $this->repository = $orderRepository;
    }
}
```
And in my repository

```php
class OrderRepository extends ServiceEntityRepository implements IOrderRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, OrderEntity::class);
    }
    
    public function get($id){
        $orderEntity = $this->find($id);
        
        $order = new Order($this);
        $order->setBasketId($orderEntity->getBasket()->getId())
            ->setQuantity($orderEntity->getQuantity())
            ->setProductId($orderEntity->getProduct()->id)
            ->setCreatedAt($orderEntity->getCreatedAt());
        return $order;
    }
}

```
How should I do to get the product of an order when I have an order.
Knowing that I have the Id of the product, I can get the product from my repository, but It will generate extra query while the result (ProductEntity) was already loaded into my repository when I fetch the Order entity.
And also, this can't be done from the view (twig template).

**Comment by Nikoms** [comment]
You can add extra code in your use case. First it will take the order and then ask to another repository, the products. "Merge" these 2 results in one object and give this object to your view.

Yes it's 2 SQL queries :) - Probably not optimized, but the next step (if you have reaaaaaally have performance issue), is to create one query that return everything at once... But it won't be entities. Just "view object" (A bit like CQRS)

**Comment by aurelmegn** [comment]
Yes, thanks
